spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GYCcom
    username: root
    password: 19530507
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: blog-backend
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.hibernate: warn
    org.springframework: info
    com.example: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: com.xiaominfo.knife4j.demo.web

knife4j:
  enable: false

---
# Production environment configuration
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate: warn
    org.springframework: warn
    com.example: info

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
