# Production environment configuration (Supabase Transaction Pooler)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # Supabase Transaction Pooler (port 6543) for better concurrency
    # Direct connection would use port 5432, but pooler is recommended for production
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      leak-detection-threshold: 60000
      # Critical: Disable prepared statement cache for Transaction Pooler compatibility
      data-source-properties:
        # PostgreSQL driver properties to disable prepared statement caching
        prepareStatementCacheQueries: 0
        prepareStatementCacheSizeMiB: 0
        cachePreparedStatements: false
        # Additional properties for pooler compatibility
        preferQueryMode: simple
        # Disable server-side prepared statements
        prepareThreshold: 0
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate # Use validate in production for safety
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Disable Hibernate's prepared statement cache for Supabase Transaction Pooler
        connection.provider_disables_autocommit: true
        jdbc.batch_size: 25
        jdbc.batch_versioned_data: true
        order_inserts: true
        order_updates: true
        # Critical: Disable prepared statement caching for pooler compatibility
        statement_cache.size: 0
        # Disable query plan cache
        query.plan_cache_max_size: 0
        # Use simple query mode for better pooler compatibility
        jdbc.use_streams_for_binary: false

# Production logging configuration
logging:
  level:
    org.hibernate: warn
    org.springframework: warn
    com.example: info
    org.hibernate.SQL: warn
    # Log connection pool issues
    com.zaxxer.hikari: warn
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# Disable Swagger UI in production for security
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Disable Knife4j in production
knife4j:
  enable: false

# Production server configuration
server:
  error:
    include-stacktrace: never
    include-message: never
  # Enable compression for better performance
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
