# Development environment configuration
spring:
  datasource:
    url: ${LOCAL_DB_URL:jdbc:postgresql://localhost:5432/gyccom}
    username: ${LOCAL_DB_USERNAME:gyc}
    password: ${LOCAL_DB_PASSWORD:changeme}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Development logging configuration
logging:
  level:
    org.hibernate: warn
    org.springframework: info
    com.example: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# Enable Swagger UI in development
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# Enable Knife4j in development
knife4j:
  enable: true
